version: "3"

services:
  app:
    container_name: its-my-party
    platform: linux/amd64             # linux/amd64 / linux/arm64/v8
    tty: true                         # false for `entrypoint` in Dockerfile
    stdin_open: true                  # false for `entrypoint` in Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000/tcp"               # host:container
    networks:
      - app-tier
    volumes:
      - .:/app
    working_dir: /app

networks:
  app-tier:
    driver: bridge
    external: true
