version: "3.0"

dotenv: ['.env']

env:
  TLD:
    sh: "echo {{.TASKFILE_DIR}}"              # absolute path
    # sh: "basename ${{.TASKFILE_DIR}}"       # directory name
  INSTA_K8S: ./bin/install_microk8s.sh
  COMPOSE_FILE: docker-compose.yml

vars:

tasks:
  print:
    - |
      echo -e "TLD:\t\t$TLD"
      echo -e "REGISTRY_URL:\t$REGISTRY_URL"
      echo -e "USER_NAME:\t$USER_NAME"
      echo -e "SERVICE:\t$SERVICE"

  default:
    desc: "Default task"
    cmds:
      - task --list

  all:
    desc: "Run all tasks"
    deps:
      - enable_registry
      - build
      - push

  enable_registry:
    desc: "Enable the microk8s registry addon"
    cmds:
      - microk8s enable registry --size=20Gi
      - echo "Follow the instructions at https://microk8s.io/docs/registry-built-in to add the registry to your docker config"
    status:
      - test "$(microk8s status --wait-ready --addon registry)" = "enabled"

  # TODO: add conditional to login differently based on registry
  login:
    desc: "Login to the registry"
    run: once
    cmds:
      - echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${USER_NAME}" --password-stdin

  build:
    desc: "Build the docker image"
    cmds:
      - docker build -t "${REGISTRY_URL}/${USER_NAME}/${SERVICE}:latest" "{{.TLD}}"

  push:
    desc: "Push the docker image to the registry"
    deps:
      - build
    cmds:
      - docker push "${REGISTRY_URL}/${USER_NAME}/${SERVICE}"
