version: "3.0"

vars:
  REPO_DIR: "$(git rev-parse --show-toplevel)"

tasks:
  all:
    deps:
      - enable_registry
      - build
      - push

  enable_registry:
    cmds:
      - microk8s enable registry --size=20Gi
      - echo "Follow the instructions at https://microk8s.io/docs/registry-built-in to add the registry to your docker config"
    status:
      - test "$(microk8s status --wait-ready --addon registry)" = "enabled"

  build:
    deps:
      - enable_registry
    cmds:
      - docker build -t localhost:32000/its-my-party:latest {{.REPO_DIR}}

  push:
    deps:
      - build
    cmds:
      - docker push localhost:32000/its-my-party
