# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: itsmyparty-ca-tsl
# spec:
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   subject:
#     organizations:
#       - testorganization
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   # TODO: change to secret/configmap
#   dnsNames:
#     - itsmyparty.ing
#   secretName: itsmyparty-ca-tsl
#   issuerRef:
#     name: ca-issuer
#     kind: Issuer
#     group: cert-manager.
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: my-service-ca-tsl
# spec:
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   subject:
#     organizations:
#       - testorganization
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   # TODO: change to secret/configmap
#   dnsNames:
#     - my-service.itsmyparty.ing
#   secretName: my-service-ca-tsl
#   issuerRef:
#     name: ca-issuer
#     kind: Issuer
#     group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www
spec:
  secretName: www-tls
  privateKey:
    rotationPolicy: Always
  commonName: www.itsmyparty.ing
  dnsNames:
    - www.itsmyparty.ing
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
