# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: ca-issuer
# spec:
#   acme:
#     # TODO: change to secret before committing
#     email: user@example.com
#     # server: https://acme-v02.api.letsencrypt.org/directory
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: issuer-key
#     solvers:
#     - dns01:
#         cloudflare:
#           # TODO: change to secret
#           email: user@example.com
#           apiTokenSecretRef:
#             name: cloudflare-api-key-secret
#             key: api-key
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: lets-encrypt
# spec:
#   acme:
#     email: user@example.com
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: lets-encrypt-private-key
#     solvers:
#       - http01:
#           ingress:
#             class: public
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-microk8s
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: user@example.com
#     privateKeySecretRef:
#       name: letsencrypt-microk8s
#     solvers:
#       - http01:
#           ingress:
#             class: public
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: user@example.com
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
