service: its-my-party

image: ghcr.io/pythoninthegrass/its-my-party

servers:
  - 192.168.8.150

registry:
  server: ghcr.io
  username: pythoninthegrass
  password:
    - KAMAL_REGISTRY_PASSWORD

# Remember to run `kamal env push` after making changes!
# env:
#   clear:
#     DB_HOST: 192.168.0.2
#   secret:
#     - RAILS_MASTER_KEY

ssh:
  user: lance

# builder:
#   secrets:
#     - GITHUB_TOKEN
#   multiarch: true

healthcheck:
  cord: /tmp/kamal-cord
  path: /up
  port: 3000

boot:
  limit: 10 # default:10 (also percent: "25%")
  wait: 2

traefik:
  args:
    accesslog: true
    accesslog.format: json

# Use accessory services (secrets come from .env).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
